export const boardTemplate = {
  game: {
    board: [
      // 0Y
      [
        {
          position: [0, 0],
          player: null,
          attack: null,
          health: null,
          rarity: "",
          img: "",
          type: "empty",
          possibleMoves: [
            [0, 1],
            [1, 1],
            [1, 0],
          ],
        },
        {
          position: [0, 1],
          player: null,
          attack: null,
          health: null,
          rarity: "",
          img: "",
          type: "empty",
          possibleMoves: [
            [0, 0],
            [0, 2],
            [1, 1],
          ],
        },
        {
          position: [0, 2],
          player: null,
          attack: null,
          health: null,
          rarity: "",
          img: "",
          type: "empty",
          possibleMoves: [
            [0, 1],
            [0, 3],
            [1, 1],
            [1, 3],
            [1, 2],
          ],
        },
        {
          position: [0, 3],
          player: null,
          attack: null,
          health: null,
          rarity: "",
          img: "",
          type: "empty",
          possibleMoves: [
            [0, 2],
            [0, 4],
            [1, 3],
          ],
        },
        {
          position: [0, 4],
          player: null,
          attack: null,
          health: null,
          rarity: "",
          img: "",
          type: "empty",
          possibleMoves: [
            [0, 3],
            [1, 4],
            [1, 3],
          ],
        },
      ],
      // 1Y
      [
        {
          position: [1, 0],
          player: null,
          attack: null,
          health: null,
          rarity: "",
          img: "",
          type: "empty",
          possibleMoves: [
            [0, 0],
            [1, 1],
            [2, 0],
          ],
        },
        {
          position: [1, 1],
          player: null,
          attack: null,
          health: null,
          rarity: "",
          img: "",
          type: "empty",
          possibleMoves: [
            [0, 0],
            [0, 1],
            [1, 2],
            [1, 0],
            [1, 2],
            [2, 0],
            [2, 1],
            [2, 2],
          ],
        },
        {
          position: [1, 2],
          player: null,
          attack: null,
          health: null,
          rarity: "",
          img: "",
          type: "empty",
          possibleMoves: [
            [0, 2],
            [1, 1],
            [1, 3],
            [2, 2],
          ],
        },
        {
          position: [1, 3],
          player: null,
          attack: null,
          health: null,
          rarity: "",
          img: "",
          type: "empty",
          possibleMoves: [
            [0, 2],
            [0, 3],
            [0, 4],
            [1, 2],
            [1, 4],
            [2, 2],
            [2, 3],
            [2, 4],
          ],
        },
        {
          position: [1, 4],
          player: null,
          attack: null,
          health: null,
          rarity: "",
          img: "",
          type: "empty",
          possibleMoves: [
            [0, 4],
            [2, 4],
            [1, 3],
          ],
        },
      ],
      // 2Y
      [
        {
          position: [2, 0],
          player: null,
          attack: null,
          health: null,
          rarity: "",
          img: "",
          type: "empty",
          possibleMoves: [
            [1, 0],
            [3, 0],
            [2, 1],
            [1, 1],
            [3, 1],
          ],
        },
        {
          position: [2, 1],
          player: null,
          attack: null,
          health: null,
          rarity: "",
          img: "",
          type: "empty",
          possibleMoves: [
            [1, 1],
            [3, 1],
            [2, 0],
            [2, 2],
          ],
        },
        {
          position: [2, 2],
          player: null,
          attack: null,
          health: null,
          rarity: "",
          img: "",
          type: "empty",
          possibleMoves: [
            [2, 1],
            [2, 3],
            [1, 2],
            [3, 2],
            [3, 1],
            [3, 3],
            [1, 1],
            [1, 3],
          ],
        },
        {
          position: [2, 3],
          player: null,
          attack: null,
          health: null,
          rarity: "",
          img: "",
          type: "empty",
          possibleMoves: [
            [1, 3],
            [3, 3],
            [2, 4],
            [2, 2],
          ],
        },
        {
          position: [2, 4],
          player: null,
          attack: null,
          health: null,
          rarity: "",
          img: "",
          type: "empty",
          possibleMoves: [
            [1, 4],
            [3, 4],
            [2, 3],
          ],
        },
      ],
      //3Y
      [
        {
          position: [3, 0],
          player: null,
          attack: null,
          health: null,
          rarity: "",
          img: "",
          type: "empty",
          possibleMoves: [
            [2, 0],
            [4, 0],
            [3, 1],
          ],
        },
        {
          position: [3, 1],
          player: null,
          attack: null,
          health: null,
          rarity: "",
          img: "",
          type: "empty",
          possibleMoves: [
            [2, 1],
            [2, 2],
            [2, 0],
            [3, 0],
            [3, 2],
            [4, 0],
            [4, 1],
            [4, 2],
          ],
        },
        {
          position: [3, 2],
          player: null,
          attack: null,
          health: null,
          rarity: "",
          img: "",
          type: "empty",
          possibleMoves: [
            [2, 2],
            [3, 1],
            [4, 2],
            [3, 3],
          ],
        },
        {
          position: [3, 3],
          player: null,
          attack: null,
          health: null,
          rarity: "",
          img: "",
          type: "empty",
          possibleMoves: [
            [2, 3],
            [2, 4],
            [2, 2],
            [3, 2],
            [3, 4],
            [4, 2],
            [4, 3],
            [4, 4],
          ],
        },
        {
          position: [3, 4],
          player: null,
          attack: null,
          health: null,
          rarity: "",
          img: "",
          type: "empty",
          possibleMoves: [
            [2, 4],
            [3, 3],
            [4, 4],
          ],
        },
      ],
      //4Y
      [
        {
          position: [4, 0],
          player: null,
          attack: null,
          health: null,
          rarity: "",
          img: "",
          type: "empty",
          possibleMoves: [
            [3, 0],
            [4, 1],
          ],
        },
        {
          position: [4, 1],
          player: null,
          attack: null,
          health: null,
          rarity: "",
          img: "",
          type: "empty",
          possibleMoves: [
            [4, 0],
            [4, 2],
            [3, 1],
          ],
        },
        {
          position: [4, 2],
          player: null,
          attack: null,
          health: null,
          rarity: "",
          img: "",
          type: "empty",
          possibleMoves: [
            [4, 1],
            [4, 3],
            [3, 1],
            [3, 2],
            [3, 3],
          ],
        },
        {
          position: [4, 3],
          player: null,
          attack: null,
          health: null,
          rarity: "",
          img: "",
          type: "empty",
          possibleMoves: [
            [4, 3],
            [4, 1],
            [3, 1],
            [3, 2],
            [3, 3],
          ],
        },
        {
          position: [4, 4],
          player: null,
          attack: null,
          health: null,
          rarity: "",
          img: "",
          type: "empty",
          possibleMoves: [
            [4, 3],
            [3, 4],
            [3, 3],
          ],
        },
      ],
    ],
  },
};
